{
 "title": "Node / Network",
 "tags": [
  "prometheus",
  "node-exporter",
  "portefaix-linux-node"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info{sysname!=\"Darwin\", job=\"node-exporter\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\", job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Interfaces Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_network_up{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_network_carrier{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8"
    },
    {
     "expr": "node_arp_entries{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_network_mtu_bytes{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_network_speed_bytes{job=~\"$job\",instance=~\"$instance\"} * 8"
    },
    {
     "expr": "node_network_transmit_queue_length{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_network_info{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network interfaces utilisation by device and direction.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} transmitted"
    }
   ]
  },
  {
   "title": "Network Interfaces Carrier Status",
   "type": "status-history",
   "description": "Network Interfaces Carrier Status",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_network_carrier{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "description": "errors received: Total number of bad packets received on this network device. This counter must include events counted by rx_length_errors, rx_crc_errors, rx_frame_errors and other errors not otherwise counted.\n\nerrors transmitted: Total number of transmit problems. This counter must include events counter by tx_aborted_errors, tx_carrier_errors, tx_fifo_errors, tx_heartbeat_errors, tx_window_errors and other errors not otherwise counted.\n\nhttps://docs.kernel.org/networking/statistics.html\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} transmitted"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "timeseries",
   "description": "drops received: Number of packets received but not processed, e.g. due to lack of resources or unsupported protocol. For hardware interfaces this counter may include packets discarded due to L2 address filtering but should not include packets dropped by the device due to buffer exhaustion which are counted separately in rx_missed_errors (since procfs folds those two counters together).\n\ndrops transmitted: Number of packets dropped on their way to transmission, e.g. due to lack of resources.\nhttps://docs.kernel.org/networking/statistics.html\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} transmitted"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "description": "packets received: Number of good packets received by the interface. \nFor hardware interfaces counts all good packets received from the device by the host, including packets which host had to drop at various stages of processing (even in the driver).\n\npackets transmitted: Number of packets successfully transmitted. \nFor hardware interfaces counts packets which host was able to successfully hand over to the device,\nwhich does not necessarily mean that packets had been successfully transmitted out of the device, only that device acknowledged it copied them out of host memory.\n\nhttps://docs.kernel.org/networking/statistics.html\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} transmitted"
    }
   ]
  },
  {
   "title": "Multicast Packets",
   "type": "timeseries",
   "description": "Multicast packets received and transmitted.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_multicast_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} transmitted"
    }
   ]
  },
  {
   "title": "Network FIFO",
   "type": "timeseries",
   "description": "Network FIFO (First-In, First-Out) refers to a buffer used by the network stack to store packets in a queue.\nIt is a mechanism used to manage network traffic and ensure that packets are delivered to their destination in the order they were received.\nPackets are stored in the FIFO buffer until they can be transmitted or processed further.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} transmitted"
    }
   ]
  },
  {
   "title": "Compressed Packets",
   "type": "timeseries",
   "description": "compressed received: \nNumber of correctly received compressed packets. This counters is only meaningful for interfaces which support packet compression (e.g. CSLIP, PPP).\n\ncompressed transmitted:\nNumber of transmitted compressed packets. This counters is only meaningful for interfaces which support packet compression (e.g. CSLIP, PPP).\n\nhttps://docs.kernel.org/networking/statistics.html\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "irate(node_network_transmit_compressed_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} transmitted"
    }
   ]
  },
  {
   "title": "NF Conntrack",
   "type": "timeseries",
   "description": "NF Conntrack is a component of the Linux kernel's netfilter framework that provides stateful packet inspection to track and manage network connections,\nenforce firewall rules, perform NAT, and manage network address/port translation.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "NF conntrack limits"
    }
   ]
  },
  {
   "title": "Softnet Packets",
   "type": "timeseries",
   "description": "Softnet packets are received by the network and queued for processing by the kernel's networking stack.\nSoftnet packets are usually generated by network traffic that is directed to the local host, and they are typically processed by the kernel's networking subsystem before being passed on to the relevant application. \n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_softnet_processed_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu }} proccessed"
    },
    {
     "expr": "irate(node_softnet_dropped_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu }} dropped"
    }
   ]
  },
  {
   "title": "Softnet Out of Quota",
   "type": "timeseries",
   "description": "\"Softnet Out of Quota\" is a network-related metric in Linux that measures the number of times the kernel's softirq processing was unable to handle incoming network traffic due to insufficient softirq processing capacity.\nThis means that the kernel has reached its processing capacity limit for incoming packets, and any additional packets will be dropped or deferred.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_softnet_times_squeezed_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}} out of quota"
    }
   ]
  },
  {
   "title": "Network Sockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sockets in use",
   "type": "timeseries",
   "description": "Number of sockets currently in use.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 sockets in use"
    }
   ]
  },
  {
   "title": "Sockets TCP",
   "type": "timeseries",
   "description": "TCP sockets are used for establishing and managing network connections between two endpoints over the TCP/IP protocol.\n\nOrphan sockets: If a process terminates unexpectedly or is terminated without closing its sockets properly, the sockets may become orphaned.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "node_sockstat_TCP6_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 In use"
    },
    {
     "expr": "node_sockstat_TCP_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 In use"
    },
    {
     "expr": "node_sockstat_TCP_orphan{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Orphan sockets"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Time wait"
    }
   ]
  },
  {
   "title": "Sockets UDP",
   "type": "timeseries",
   "description": "UDP (User Datagram Protocol) and UDPlite (UDP-Lite) sockets are used for transmitting and receiving data over the UDP and UDPlite protocols, respectively.\nBoth UDP and UDPlite are connectionless protocols that do not provide a reliable data delivery mechanism.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 UDPLITE in use"
    },
    {
     "expr": "node_sockstat_UDP_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 UDP in use"
    },
    {
     "expr": "node_sockstat_UDPLITE6_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 UDPLITE in use"
    },
    {
     "expr": "node_sockstat_UDP6_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 UDP in use"
    }
   ]
  },
  {
   "title": "Sockets Memory",
   "type": "timeseries",
   "description": "Memory currently in use for sockets.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_mem{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory pages allocated for TCP sockets"
    },
    {
     "expr": "node_sockstat_UDP_mem{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory pages allocated for UDP sockets"
    },
    {
     "expr": "node_sockstat_TCP_mem_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory bytes allocated for TCP sockets"
    },
    {
     "expr": "node_sockstat_UDP_mem_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Memory bytes allocated for UDP sockets"
    }
   ]
  },
  {
   "title": "Sockets Other",
   "type": "timeseries",
   "description": "FRAG (IP fragment) sockets: Used to receive and process fragmented IP packets. FRAG sockets are useful in network monitoring and analysis.\n\nRAW sockets: Allow applications to send and receive raw IP packets directly without the need for a transport protocol like TCP or UDP.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_FRAG_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 Frag sockets in use"
    },
    {
     "expr": "node_sockstat_FRAG6_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 Frag sockets in use"
    },
    {
     "expr": "node_sockstat_RAW_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv4 Raw sockets in use"
    },
    {
     "expr": "node_sockstat_RAW6_inuse{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "IPv6 Raw sockets in use"
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IP octets",
   "type": "timeseries",
   "description": "Rate of IP octets received and transmitted.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "oct/s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Octets received"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Octets transmitted"
    }
   ]
  },
  {
   "title": "TCP segments",
   "type": "timeseries",
   "description": "Rate of TCP segments received and transmitted.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "seg/s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_InSegs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP received"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP transmitted"
    }
   ]
  },
  {
   "title": "TCP errors rate",
   "type": "timeseries",
   "description": "Rate of TCP errors.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP overflow"
    },
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP ListenDrops - SYNs to LISTEN sockets ignored"
    },
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP SYN rentransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP retransmitted segments, containing one or more previously transmitted octets"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP received with errors"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutRsts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "TCP segments sent with RST flag"
    }
   ]
  },
  {
   "title": "UDP datagrams",
   "type": "timeseries",
   "description": "Rate of UDP datagrams received and transmitted.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "dat/s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP received"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP transmitted"
    },
    {
     "expr": "irate(node_netstat_Udp6_InDatagrams{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 received"
    },
    {
     "expr": "irate(node_netstat_Udp6_OutDatagrams{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 transmitted"
    }
   ]
  },
  {
   "title": "UDP errors rate",
   "type": "timeseries",
   "description": "Rate of UDP datagrams received and transmitted with errors.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_UdpLite_InErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDPLite InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp6_InErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP NoPorts"
    },
    {
     "expr": "irate(node_netstat_Udp6_NoPorts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 NoPorts"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP receive buffer errors"
    },
    {
     "expr": "irate(node_netstat_Udp6_RcvbufErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 receive buffer errors"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP send buffer errors"
    },
    {
     "expr": "irate(node_netstat_Udp6_SndbufErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UDP6 send buffer errors"
    }
   ]
  },
  {
   "title": "ICMP messages",
   "type": "timeseries",
   "description": "Rate of ICMP messages, like 'ping', received and transmitted.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InMsgs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP received"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutMsgs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP transmitted"
    },
    {
     "expr": "irate(node_netstat_Icmp6_InMsgs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP6 received"
    },
    {
     "expr": "irate(node_netstat_Icmp6_OutMsgs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP6 transmitted"
    }
   ]
  },
  {
   "title": "ICMP errors rate",
   "type": "timeseries",
   "description": "Rate of ICMP messages received and transmitted with errors.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP Errors"
    },
    {
     "expr": "irate(node_netstat_Icmp6_InErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ICMP6 Errors"
    }
   ]
  }
 ]
}